package stewlang

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

var attrRegex = regexp.MustCompile(`([a-zA-Z0-9_-]+)(?:=(?:"([^"]*)"|'([^']*)'|{{([^}]+)}}))?`)

func buildWasm(name string, nodes []Node, bindings string, clientImports []string, usesStewData bool) (string, error) {
	if _, err := exec.LookPath("tinygo"); err != nil {
		return "", fmt.Errorf("tinygo is not installed. Please install TinyGo to compile WebAssembly bindings: https://tinygo.org/getting-started/")
	}

	var wasmBuf bytes.Buffer
	wasmBuf.WriteString("package main\n\n")
	wasmBuf.WriteString("import (\n\t\"github.com/ZiplEix/stew/sdk/wasm\"\n")
	for _, imp := range clientImports {
		if imp == "\"stew/data\"" {
			wasmBuf.WriteString("\t\"github.com/ZiplEix/stew/sdk/wasm/data\"\n")
			continue
		}
		wasmBuf.WriteString("\t" + imp + "\n")
	}
	wasmBuf.WriteString(")\n\n")

	var structDefinitions typesBuilder
	nodes = extractTypes(nodes, &structDefinitions, "client")
	if structDefinitions.Len() > 0 {
		wasmBuf.WriteString(structDefinitions.String() + "\n")
	}

	wasmBuf.WriteString("\nfunc main() {\n")
	if usesStewData {
		wasmBuf.WriteString("\tdata := data.Data\n")
	}

	// Add client goscripts (excluding parsed imports and types)
	hasClientCode := false
	for _, n := range nodes {
		if gs, ok := n.(NodeGoScript); ok && gs.Context == "client" {
			lines := strings.Split(gs.Content, "\n")
			for _, line := range lines {
				if !strings.HasPrefix(strings.TrimSpace(line), "import ") {
					wasmBuf.WriteString("\t" + line + "\n")
				}
			}
			hasClientCode = true
		}
	}

	// If there's no actual client code and no bindings, just skip
	if !hasClientCode && bindings == "" {
		return "", nil
	}

	wasmBuf.WriteString("\n\t// DOM Bindings generated by Stew\n")
	wasmBuf.WriteString(bindings)
	wasmBuf.WriteString("\n\twasm.StartReactivityLoop()\n")
	wasmBuf.WriteString("}\n")

	tmpPath := filepath.Join(os.TempDir(), fmt.Sprintf("stew_main_wasm_%s.go", name))
	if err := os.WriteFile(tmpPath, wasmBuf.Bytes(), 0644); err != nil {
		return "", err
	}

	outWasm := filepath.Join(".", "static", "wasm", name+".wasm")
	os.MkdirAll(filepath.Dir(outWasm), 0755)

	cmd := exec.Command("tinygo", "build", "-target", "wasm", "-no-debug", "-o", outWasm, tmpPath)
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	if err := cmd.Run(); err != nil {
		fmt.Printf("⚠️  TinyGo build warning: %v. Is your Go version supported?\n", err)
		return "", nil // Non-fatal, we still track
	}

	return outWasm, nil
}

func Compile(name string, pkgName string, moduleBase string, relFilePath string, input string) (string, []string, error) {
	lexer := NewLexer(input, moduleBase, relFilePath)
	tokens := lexer.Lex()

	parser := NewParser(tokens)
	nodes, err := parser.Parse()
	if err != nil {
		return "", nil, err
	}

	// First pass: extract imports from <goscript>
	var userImports []string
	var stewImports []string
	var clientImports []string
	usesStewData := extractImports(nodes, &userImports, &stewImports, &clientImports, moduleBase, relFilePath)

	isComponent := false
	if regexp.MustCompile(`^[A-Z][a-zA-Z0-9]*$`).MatchString(name) && !strings.HasSuffix(name, "Page") && name != "Layout" {
		isComponent = true
	}

	// Isomorphic processing: detect bindings & inject IDs
	var modifiedNodes []Node
	bindCounter := 0
	hasClientCode := false
	var clientBindings bytes.Buffer

	for i := 0; i < len(nodes); i++ {
		n := nodes[i]
		if bindNode, ok := n.(NodeBind); ok {
			// Orphan bindings (without a client script) will be ignored later by buildWasm check
			if i > 0 {
				if prevHTML, isHTML := modifiedNodes[len(modifiedNodes)-1].(NodeHTML); isHTML {
					bindID := fmt.Sprintf("stew-bind-%s-%d", strings.ToLower(name), bindCounter)
					bindCounter++

					// Naïve injection at the end of the HTML string pre-parsing
					prevHTML.Content += fmt.Sprintf(`id="%s" `, bindID)
					modifiedNodes[len(modifiedNodes)-1] = prevHTML

					if bindNode.IsEvent {
						clientBindings.WriteString(fmt.Sprintf("\twasm.OnEvent(\"%s\", \"%s\", func() { %s })\n", bindID, bindNode.BindType, bindNode.BindVar))
					} else {
						if bindNode.BindType == "value" {
							clientBindings.WriteString(fmt.Sprintf("\twasm.BindInput(\"%s\", &%s)\n", bindID, bindNode.BindVar))
						} else {
							clientBindings.WriteString(fmt.Sprintf("\twasm.BindContent(\"%s\", &%s)\n", bindID, bindNode.BindVar))
						}
					}
				}
			}
		} else if gs, ok := n.(NodeGoScript); ok {
			if gs.Context == "client" {
				hasClientCode = true
			}
			modifiedNodes = append(modifiedNodes, n)
		} else {
			modifiedNodes = append(modifiedNodes, n)
		}
	}
	nodes = modifiedNodes

	// Check if there is actual client script code to determine Wasm build
	// Reactive bindings alone don't trigger build if there's no script to define vars
	for _, n := range nodes {
		if gs, ok := n.(NodeGoScript); ok && gs.Context == "client" {
			hasClientCode = true
			break
		}
	}

	// Generate unique Wasm name to avoid clashes between nested pages
	wasmName := strings.ReplaceAll(strings.TrimSuffix(relFilePath, ".stew"), "/", "_")
	wasmName = strings.ReplaceAll(wasmName, "@", "")
	wasmName = strings.ToLower(wasmName)

	// Build WebAssembly if client code is present
	var generatedArtifacts []string
	if hasClientCode {
		wasmPath, err := buildWasm(wasmName, nodes, clientBindings.String(), clientImports, usesStewData)
		if err != nil {
			fmt.Printf("⚠️  TinyGo build warning: %v.\n", err)
		} else if wasmPath != "" {
			generatedArtifacts = append(generatedArtifacts, wasmPath)
		}
	}

	var pkgLevel typesBuilder
	nodes = extractTypes(nodes, &pkgLevel, "server")

	pageName := name
	if !isComponent && pageName != "Layout" {
		if len(pageName) > 0 {
			pageName = strings.ToUpper(pageName[0:1]) + pageName[1:]
		}
		if !strings.HasSuffix(pageName, "Page") {
			pageName += "Page"
		}
	}

	var bodyBuf bytes.Buffer
	if isComponent {
		bodyBuf.WriteString(fmt.Sprintf("func %s(w io.Writer, data stew.PageData, props %sProps, slot func()) {\n\n", pageName, pageName))
	} else if pageName == "Layout" {
		bodyBuf.WriteString("func Layout(w io.Writer, data stew.PageData, slot func()) {\n\n")
	} else {
		bodyBuf.WriteString(fmt.Sprintf("func %s(w io.Writer, data stew.PageData) {\n\n", pageName))
	}

	// Server emit
	// We only emit "server" goscripts
	var serverNodes []Node
	for _, n := range nodes {
		if gs, ok := n.(NodeGoScript); ok {
			if gs.Context == "server" {
				serverNodes = append(serverNodes, gs)
			}
		} else {
			serverNodes = append(serverNodes, n)
		}
	}

	if err := emitNodes(&bodyBuf, serverNodes, lexer.ValidComponents); err != nil {
		return "", nil, err
	}

	// Inject Wasm Bootstrap if client code
	if hasClientCode {
		bodyBuf.WriteString("\tdataJSON, _ := json.Marshal(data)\n")
		bodyBuf.WriteString("\tw.Write([]byte(`<script type=\"application/json\" id=\"stew-pagedata\">`))\n")
		bodyBuf.WriteString("\tw.Write(dataJSON)\n")
		bodyBuf.WriteString("\tw.Write([]byte(`</script>`))\n")

		wasmPath := fmt.Sprintf("/static/wasm/%s.wasm", wasmName)
		bootstrap := fmt.Sprintf(`<script src="/static/wasm/wasm_exec.js"></script><script>const go = new Go(); WebAssembly.instantiateStreaming(fetch("%s"), go.importObject).then((result) => { go.run(result.instance); });</script>`, wasmPath)
		bodyBuf.WriteString(fmt.Sprintf("\tw.Write([]byte(`%s`))\n", bootstrap))
	}

	bodyBuf.WriteString("}\n")
	bodyStr := bodyBuf.String()

	// codeOnlyStr strips the raw HTML string content (inside backtick literals)
	// so we don't false-positive on "fmt." or "html." that appear inside HTML display text.
	codeOnlyStr := stripBacktickContent(bodyStr)

	// Final Import block generation
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Stew-Lang. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	// Collect unique imports and verify usage
	importPaths := make(map[string]bool)
	importPaths["\"io\""] = true
	importPaths["\"github.com/ZiplEix/stew/sdk/stew\""] = true
	if hasClientCode {
		importPaths["\"encoding/json\""] = true
	}

	// Dynamic detection of fmt and html through codeOnlyStr
	if strings.Contains(codeOnlyStr, "fmt.") {
		importPaths["\"fmt\""] = true
	}
	if strings.Contains(codeOnlyStr, "html.EscapeString") || strings.Contains(codeOnlyStr, "html.") {
		importPaths["\"html\""] = true
	}

	// Check user imports usage
	for _, imp := range userImports {
		cleanImp := strings.Trim(imp, "\"")
		alias := ""
		parts := strings.Fields(cleanImp)
		if len(parts) == 2 {
			alias = parts[0]
		} else {
			alias = path.Base(strings.Trim(cleanImp, "\"'"))
		}
		if strings.Contains(codeOnlyStr, alias+".") || strings.Contains(pkgLevel.String(), alias+".") {
			importPaths[imp] = true
		}
	}

	// Check stew component imports usage
	for _, imp := range stewImports {
		cleanImp := strings.Trim(imp, "\"")
		alias := path.Base(cleanImp)
		if strings.Contains(codeOnlyStr, alias+".") || strings.Contains(pkgLevel.String(), alias+".") {
			importPaths[imp] = true
		}
	}

	buf.WriteString("import (\n")
	for imp := range importPaths {
		buf.WriteString("\t" + imp + "\n")
	}
	buf.WriteString(")\n\n")

	if pkgLevel.Len() > 0 {
		buf.WriteString(pkgLevel.String() + "\n")
	}

	if isComponent {
		matched, _ := regexp.MatchString(fmt.Sprintf(`type\s+%sProps\s+struct`, pageName), pkgLevel.String())
		if !matched {
			buf.WriteString(fmt.Sprintf("type %sProps struct {}\n\n", pageName))
		}
	}

	buf.WriteString(bodyStr)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Output unformatted for debugging if formatting fails
		return buf.String(), generatedArtifacts, fmt.Errorf("error formatting generated code: %v\nCode:\n%s", err, buf.String())
	}

	return string(formatted), generatedArtifacts, nil
}

func extractImports(nodes []Node, userImports *[]string, stewImports *[]string, clientImports *[]string, moduleBase string, relFilePath string) bool {
	usesStewData := false
	for _, n := range nodes {
		if gs, ok := n.(NodeGoScript); ok {
			lines := strings.Split(gs.Content, "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "import ") {
					importStr := strings.TrimSpace(strings.TrimPrefix(line, "import "))
					importStr = strings.Trim(importStr, "\"'")

					if importStr == "stew/data" {
						usesStewData = true
					}

					if gs.Context == "client" {
						*clientImports = append(*clientImports, "\""+importStr+"\"")
						continue
					}

					if strings.HasSuffix(importStr, ".stew") {
						dir := importStr
						lastSlash := strings.LastIndex(dir, "/")
						if lastSlash != -1 {
							dir = dir[:lastSlash]
						} else {
							dir = "."
						}

						currentDir := "."
						lastFileSlash := strings.LastIndex(relFilePath, "/")
						if lastFileSlash != -1 {
							currentDir = relFilePath[:lastFileSlash]
						}

						if dir == "." {
							continue
						}

						fullPkgPath := path.Join(moduleBase, currentDir, dir)
						*stewImports = append(*stewImports, "\""+fullPkgPath+"\"")
						continue
					}
					*userImports = append(*userImports, "\""+importStr+"\"")
				}
			}
		} else if b, ok := n.(NodeIf); ok {
			if extractImports(b.Body, userImports, stewImports, clientImports, moduleBase, relFilePath) {
				usesStewData = true
			}
			if extractImports(b.ElseBody, userImports, stewImports, clientImports, moduleBase, relFilePath) {
				usesStewData = true
			}
		} else if b, ok := n.(NodeEach); ok {
			if extractImports(b.Body, userImports, stewImports, clientImports, moduleBase, relFilePath) {
				usesStewData = true
			}
		} else if b, ok := n.(NodeComponent); ok {
			if extractImports(b.Body, userImports, stewImports, clientImports, moduleBase, relFilePath) {
				usesStewData = true
			}
		}
	}
	return usesStewData
}

type typesBuilder struct {
	strings.Builder
}

func extractTypes(nodes []Node, pkgLevel *typesBuilder, targetContext string) []Node {
	var out []Node
	for _, n := range nodes {
		switch node := n.(type) {
		case NodeGoScript:
			if node.Context != targetContext {
				out = append(out, node)
				continue
			}

			lines := strings.Split(node.Content, "\n")
			var remainingLines []string

			inTypeBlock := false
			braceCount := 0
			var typeBlock strings.Builder

			for _, line := range lines {
				trimmed := strings.TrimSpace(line)
				if !inTypeBlock {
					if strings.HasPrefix(trimmed, "type ") && strings.Contains(trimmed, " struct") {
						inTypeBlock = true
						typeBlock.WriteString(line + "\n")
						braceCount += strings.Count(line, "{") - strings.Count(line, "}")
						if braceCount <= 0 && strings.Contains(line, "{") {
							pkgLevel.WriteString(typeBlock.String())
							typeBlock.Reset()
							inTypeBlock = false
						}
					} else {
						remainingLines = append(remainingLines, line)
					}
				} else {
					typeBlock.WriteString(line + "\n")
					braceCount += strings.Count(line, "{") - strings.Count(line, "}")
					if braceCount <= 0 {
						pkgLevel.WriteString(typeBlock.String())
						typeBlock.Reset()
						inTypeBlock = false
					}
				}
			}
			node.Content = strings.Join(remainingLines, "\n")
			out = append(out, node)

		case NodeIf:
			node.Body = extractTypes(node.Body, pkgLevel, targetContext)
			node.ElseBody = extractTypes(node.ElseBody, pkgLevel, targetContext)
			out = append(out, node)
		case NodeEach:
			node.Body = extractTypes(node.Body, pkgLevel, targetContext)
			out = append(out, node)
		case NodeComponent:
			node.Body = extractTypes(node.Body, pkgLevel, targetContext)
			out = append(out, node)
		default:
			out = append(out, node)
		}
	}
	return out
}

func emitNodes(buf *bytes.Buffer, nodes []Node, validComps map[string]string) error {
	for _, n := range nodes {
		switch node := n.(type) {
		case NodeHTML:
			emitHTML(buf, node.Content)
		case NodeExpression:
			emitExpression(buf, node.Content)
		case NodeGoScript:
			// Emit goscript minus lines purely starting with "import "
			lines := strings.Split(node.Content, "\n")
			for _, line := range lines {
				if !strings.HasPrefix(strings.TrimSpace(line), "import ") {
					buf.WriteString("\t\t" + line + "\n")
				}
			}
		case NodeIf:
			buf.WriteString(fmt.Sprintf("\tif %s {\n", node.Condition))
			if err := emitNodes(buf, node.Body, validComps); err != nil {
				return err
			}
			if len(node.ElseBody) > 0 {
				buf.WriteString("\t} else {\n")
				if err := emitNodes(buf, node.ElseBody, validComps); err != nil {
					return err
				}
			}
			buf.WriteString("\t}\n")
		case NodeEach:
			parts := strings.Split(node.Iterator, " as ")
			if len(parts) != 2 {
				return fmt.Errorf("invalid each format: %s", node.Iterator)
			}
			slice := strings.TrimSpace(parts[0])
			vars := strings.Split(parts[1], ",")

			varName := "item"
			idxName := "_"
			if len(vars) == 1 {
				varName = strings.TrimSpace(vars[0])
			} else if len(vars) == 2 {
				varName = strings.TrimSpace(vars[0])
				idxName = strings.TrimSpace(vars[1])
			}

			buf.WriteString(fmt.Sprintf("\tfor %s, %s := range %s {\n", idxName, varName, slice))
			if err := emitNodes(buf, node.Body, validComps); err != nil {
				return err
			}
			buf.WriteString("\t}\n")

		case NodeComponent:
			// parse pros
			props := parseAttributes(node.TagContent)

			// struct initialization
			var structValues []string

			for k, v := range props {
				fieldName := k
				if len(fieldName) > 0 {
					fieldName = strings.ToUpper(fieldName[0:1]) + fieldName[1:]
				}
				structValues = append(structValues, fmt.Sprintf("%s: %s", fieldName, v))
			}

			structInit := fmt.Sprintf("%sProps{%s}", node.TagName, strings.Join(structValues, ", "))

			alias := validComps[node.TagName]

			// write component call
			if node.SelfClosing || len(node.Body) == 0 {
				buf.WriteString(fmt.Sprintf("\t%s%s(w, data, %s%s, nil)\n", alias, node.TagName, alias, structInit))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s%s(w, data, %s%s, func() {\n", alias, node.TagName, alias, structInit))
				if err := emitNodes(buf, node.Body, validComps); err != nil {
					return err
				}
				buf.WriteString("\t})\n")
			}

		case NodeSlot:
			buf.WriteString("\tif slot != nil {\n\t\tslot()\n\t}\n")
		}
	}
	return nil
}

// stripBacktickContent removes the content of Go raw string literals (between backticks)
// from generated code, so that import-usage detection doesn't false-positive on
// HTML display text that happens to contain "fmt." or "html." etc.
func stripBacktickContent(s string) string {
	// Temporarily mask the backtick escape sequence used in emitHTML
	// logic: w.Write([]byte(`...` + "`" + `...`))
	s = strings.ReplaceAll(s, "` + \"`\" + `", "__B_ESC__")

	var result strings.Builder
	inBacktick := false
	for i := 0; i < len(s); i++ {
		if s[i] == '`' {
			inBacktick = !inBacktick
			result.WriteByte('`')
			continue
		}
		if !inBacktick {
			result.WriteByte(s[i])
		}
	}
	return result.String()
}

func emitHTML(buf *bytes.Buffer, content string) {
	if len(content) == 0 {
		return
	}
	// escape ` and write
	escaped := strings.ReplaceAll(content, "`", "`+\"`\"+`")
	buf.WriteString(fmt.Sprintf("\tw.Write([]byte(`%s`))\n", escaped))
}

func emitExpression(buf *bytes.Buffer, expr string) {
	expr = strings.TrimSpace(expr)

	// handle raw()
	if strings.HasPrefix(expr, "raw(") && strings.HasSuffix(expr, ")") {
		inner := expr[4 : len(expr)-1]
		buf.WriteString(fmt.Sprintf("\tw.Write([]byte(fmt.Sprint(%s)))\n", inner))
		return
	}

	buf.WriteString(fmt.Sprintf("\tw.Write([]byte(html.EscapeString(fmt.Sprint(%s))))\n", expr))
}

func parseAttributes(tagContent string) map[string]string {
	// e.g. <Button title="Hello" count={{ data.Count }} disabled>
	tagContent = strings.TrimSpace(tagContent)
	tagContent = strings.TrimPrefix(tagContent, "<")
	tagContent = strings.TrimSuffix(tagContent, "/>")
	tagContent = strings.TrimSuffix(tagContent, ">")

	// strip tag name
	idx := strings.IndexAny(tagContent, " \t\n\r")
	if idx == -1 {
		return nil
	}

	attrStr := tagContent[idx+1:]
	matches := attrRegex.FindAllStringSubmatch(attrStr, -1)

	props := make(map[string]string)

	for _, m := range matches {
		if len(m) == 0 {
			continue
		}
		key := m[1]
		if key == "" || strings.HasPrefix(key, "bind:") {
			continue
		}

		val := "true" // boolean prop like `disabled`

		if m[2] != "" {
			val = "\"" + m[2] + "\"" // string like "hello"
		} else if m[3] != "" {
			val = "\"" + m[3] + "\"" // string like 'hello'
		} else if m[4] != "" {
			val = m[4] // expression like data.Count
		}

		props[key] = val
	}

	return props
}
