package stewlang

import (
	"strings"
	"testing"
)

func TestCompilerBasic(t *testing.T) {
	input := `<goscript>import "strings"</goscript>
{{ if data.User.IsAdmin }}
    <h1>Admin: {{ strings.ToUpper(data.User.Name) }}</h1>
{{ end }}`

	output, err := Compile("profile", "pages", "github.com/ZiplEix/stew", "test.stew", input)
	if err != nil {
		t.Fatalf("Compile error: %v", err)
	}

	expectedPrefix := `// Code generated by Stew-Lang. DO NOT EDIT.
package pages`
	if !strings.HasPrefix(output, expectedPrefix) {
		t.Errorf("missing expected prefix in compile output:\n%s", output)
	}

	if !strings.Contains(output, `"strings"`) {
		t.Errorf("missing extracted import for 'strings':\n%s", output)
	}

	if !strings.Contains(output, `if data.User.IsAdmin {`) {
		t.Errorf("missing if statement:\n%s", output)
	}

	if !strings.Contains(output, `strings.ToUpper(data.User.Name)`) {
		t.Errorf("missing exact expression:\n%s", output)
	}
}

func TestCompilerEachAndComponent(t *testing.T) {
	input := `<goscript>
import "./components/UserCard.stew"
</goscript>
{{ each data.Users as u, i }}
    <UserCard user={{ u }} index="{{ i }}" />
{{ end }}`

	output, err := Compile("Components", "pages", "github.com/ZiplEix/stew", "test.stew", input)
	if err != nil {
		t.Fatalf("Compile error: %v", err)
	}

	if !strings.Contains(output, `for i, u := range data.Users {`) {
		t.Errorf("missing for loop, got: %s", output)
	}

	// Should contain dynamic component structs
	if !strings.Contains(output, "UserCardProps{User: u, Index: \"{{ i }}\"}") && !strings.Contains(output, "UserCardProps{Index: \"{{ i }}\", User: u}") {
		t.Errorf("missing dynamic struct definition for component, got:\n%s", output)
	}
	
	if !strings.Contains(output, `UserCard(w, data`) {
		t.Errorf("missing component invocation UserCard: %s", output)
	}
}

func TestCompilerComponentSignatureAndSlot(t *testing.T) {
	input := `
<goscript>
type ButtonProps struct {
    Label string
}
</goscript>
<button>{{ props.Label }} <slot /></button>
`
	output, err := Compile("Button", "pages", "github.com/ZiplEix/stew", "test.stew", input)
	if err != nil {
		t.Fatalf("Compile error: %v", err)
	}

	if !strings.Contains(output, `func Button(w io.Writer, data stew.PageData, props ButtonProps, slot func()) {`) {
		t.Errorf("Missing component signature, got:\n%s", output)
	}

	if !strings.Contains(output, `if slot != nil {`) {
		t.Errorf("Missing slot logic, got:\n%s", output)
	}
}

func TestCompilerComponentWithSlotContent(t *testing.T) {
	input := `
<goscript>
import "./components/Layout.stew"
</goscript>
<Layout title="Home">
    <p>Welcome</p>
</Layout>
`
	output, err := Compile("Page", "pages", "github.com/ZiplEix/stew", "test.stew", input)
	if err != nil {
		t.Fatalf("Compile error: %v", err)
	}

	if !strings.Contains(output, `components.LayoutProps{Title: "Home"}`) {
		t.Errorf("Missing LayoutProps initialization: \n%s", output)
	}

	if !strings.Contains(output, `components.Layout(w, data, components.LayoutProps{Title: "Home"}, func() {`) {
		t.Errorf("Missing slot closure definition: \n%s", output)
	}
}

func TestCompilerMissingEndError(t *testing.T) {
	input := `
{{ if true }}
    <p>hi</p>
`
	_, err := Compile("Test", "pages", "github.com/ZiplEix/stew", "test.stew", input)
	if err == nil {
		t.Errorf("expected error for missing {{ end }}")
	} else if !strings.Contains(err.Error(), "missing {{ end }}") {
		t.Errorf("expected missing end error format, got: %v", err)
	}
}
