package stewlang

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"regexp"
	"strings"
)

var attrRegex = regexp.MustCompile(`([a-zA-Z0-9_-]+)(?:=(?:"([^"]*)"|'([^']*)'|{{([^}]+)}}))?`)

func Compile(name string, pkgName string, moduleBase string, relFilePath string, input string) (string, error) {
	lexer := NewLexer(input, moduleBase, relFilePath)
	tokens := lexer.Lex()

	parser := NewParser(tokens)
	nodes, err := parser.Parse()
	if err != nil {
		return "", err
	}

	// First pass: extract imports from <goscript>
	var userImports []string
	var stewImports []string
	extractImports(nodes, &userImports, &stewImports, moduleBase, relFilePath)

	isComponent := false
	if regexp.MustCompile(`^[A-Z][a-zA-Z0-9]*$`).MatchString(name) && !strings.HasSuffix(name, "Page") && name != "Layout" {
		isComponent = true
	}

	var pkgLevel typesBuilder
	nodes = extractTypes(nodes, &pkgLevel)

	pageName := name
	if !isComponent && pageName != "Layout" {
		if len(pageName) > 0 {
			pageName = strings.ToUpper(pageName[0:1]) + pageName[1:]
		}
		if !strings.HasSuffix(pageName, "Page") {
			pageName += "Page"
		}
	}

	var bodyBuf bytes.Buffer
	if isComponent {
		bodyBuf.WriteString(fmt.Sprintf("func %s(w io.Writer, data stew.PageData, props %sProps, slot func()) {\n\n", pageName, pageName))
	} else if pageName == "Layout" {
		bodyBuf.WriteString("func Layout(w io.Writer, data stew.PageData, slot func()) {\n\n")
	} else {
		bodyBuf.WriteString(fmt.Sprintf("func %s(w io.Writer, data stew.PageData) {\n\n", pageName))
	}

	if err := emitNodes(&bodyBuf, nodes, lexer.ValidComponents); err != nil {
		return "", err
	}
	bodyBuf.WriteString("}\n")
	bodyStr := bodyBuf.String()

	// Third pass: dynamically manage imports
	var buf bytes.Buffer
	buf.WriteString("// Code generated by Stew-Lang. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	buf.WriteString("import (\n")
	buf.WriteString("\t\"io\"\n")

	if strings.Contains(bodyStr, "fmt.") {
		buf.WriteString("\t\"fmt\"\n")
	}
	if strings.Contains(bodyStr, "html.EscapeString") || strings.Contains(bodyStr, "html.") {
		buf.WriteString("\t\"html\"\n")
	}
	buf.WriteString("\t\"github.com/ZiplEix/stew/sdk/stew\"\n")
	
	// Print tracked User Imports
	for _, imp := range userImports {
		buf.WriteString("\t" + imp + "\n")
	}

	// Filter and Dedup compiler generated component packages
	seenImports := make(map[string]bool)
	for _, imp := range stewImports {
		if seenImports[imp] {
			continue
		}
		seenImports[imp] = true
		
		cleanImp := strings.Trim(imp, "\"")
		alias := path.Base(cleanImp)
		
		// Ensure package alias is actually used internally inside bindings/goscripts
		if strings.Contains(bodyStr, alias+".") || strings.Contains(pkgLevel.String(), alias+".") {
			buf.WriteString("\t" + imp + "\n")
		}
	}
	
	buf.WriteString(")\n\n")

	if pkgLevel.Len() > 0 {
		buf.WriteString(pkgLevel.String() + "\n")
	}

	if isComponent {
		matched, _ := regexp.MatchString(fmt.Sprintf(`type\s+%sProps\s+struct`, pageName), pkgLevel.String())
		if !matched {
			buf.WriteString(fmt.Sprintf("type %sProps struct {}\n\n", pageName))
		}
	}

	buf.WriteString(bodyStr)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Output unformatted for debugging if formatting fails
		return buf.String(), fmt.Errorf("error formatting generated code: %v\nCode:\n%s", err, buf.String())
	}

	return string(formatted), nil
}

func extractImports(nodes []Node, userImports *[]string, stewImports *[]string, moduleBase string, relFilePath string) {
	for _, n := range nodes {
		if gs, ok := n.(NodeGoScript); ok {
			lines := strings.Split(gs.Content, "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "import ") {
					importStr := strings.TrimSpace(strings.TrimPrefix(line, "import "))
					importStr = strings.Trim(importStr, "\"'")
					if strings.HasSuffix(importStr, ".stew") {
						dir := importStr
						lastSlash := strings.LastIndex(dir, "/")
						if lastSlash != -1 {
							dir = dir[:lastSlash]
						} else {
							dir = "."
						}

						currentDir := "."
						lastFileSlash := strings.LastIndex(relFilePath, "/")
						if lastFileSlash != -1 {
							currentDir = relFilePath[:lastFileSlash]
						}

						if dir == "." {
							continue
						}

						fullPkgPath := path.Join(moduleBase, currentDir, dir)
						*stewImports = append(*stewImports, "\""+fullPkgPath+"\"")
						continue
					}
					*userImports = append(*userImports, "\""+importStr+"\"")
				}
			}
		} else if b, ok := n.(NodeIf); ok {
			extractImports(b.Body, userImports, stewImports, moduleBase, relFilePath)
			extractImports(b.ElseBody, userImports, stewImports, moduleBase, relFilePath)
		} else if b, ok := n.(NodeEach); ok {
			extractImports(b.Body, userImports, stewImports, moduleBase, relFilePath)
		} else if b, ok := n.(NodeComponent); ok {
			extractImports(b.Body, userImports, stewImports, moduleBase, relFilePath)
		}
	}
}

type typesBuilder struct {
	strings.Builder
}

func extractTypes(nodes []Node, pkgLevel *typesBuilder) []Node {
	var out []Node
	for _, n := range nodes {
		switch node := n.(type) {
		case NodeGoScript:
			lines := strings.Split(node.Content, "\n")
			var remainingLines []string
			
			inTypeBlock := false
			braceCount := 0
			var typeBlock strings.Builder
			
			for _, line := range lines {
				trimmed := strings.TrimSpace(line)
				if !inTypeBlock {
					if strings.HasPrefix(trimmed, "type ") && strings.Contains(trimmed, " struct") {
						inTypeBlock = true
						typeBlock.WriteString(line + "\n")
						braceCount += strings.Count(line, "{") - strings.Count(line, "}")
						if braceCount <= 0 && strings.Contains(line, "{") {
							pkgLevel.WriteString(typeBlock.String())
							typeBlock.Reset()
							inTypeBlock = false
						}
					} else {
						remainingLines = append(remainingLines, line)
					}
				} else {
					typeBlock.WriteString(line + "\n")
					braceCount += strings.Count(line, "{") - strings.Count(line, "}")
					if braceCount <= 0 {
						pkgLevel.WriteString(typeBlock.String())
						typeBlock.Reset()
						inTypeBlock = false
					}
				}
			}
			out = append(out, NodeGoScript{Content: strings.Join(remainingLines, "\n")})
			
		case NodeIf:
			node.Body = extractTypes(node.Body, pkgLevel)
			node.ElseBody = extractTypes(node.ElseBody, pkgLevel)
			out = append(out, node)
		case NodeEach:
			node.Body = extractTypes(node.Body, pkgLevel)
			out = append(out, node)
		case NodeComponent:
			node.Body = extractTypes(node.Body, pkgLevel)
			out = append(out, node)
		default:
			out = append(out, node)
		}
	}
	return out
}

func emitNodes(buf *bytes.Buffer, nodes []Node, validComps map[string]string) error {
	for _, n := range nodes {
		switch node := n.(type) {
		case NodeHTML:
			emitHTML(buf, node.Content)
		case NodeExpression:
			emitExpression(buf, node.Content)
		case NodeGoScript:
			// Emit goscript minus lines purely starting with "import "
			lines := strings.Split(node.Content, "\n")
			for _, line := range lines {
				if !strings.HasPrefix(strings.TrimSpace(line), "import ") {
					buf.WriteString("\t\t" + line + "\n")
				}
			}
		case NodeIf:
			buf.WriteString(fmt.Sprintf("\tif %s {\n", node.Condition))
			if err := emitNodes(buf, node.Body, validComps); err != nil {
				return err
			}
			if len(node.ElseBody) > 0 {
				buf.WriteString("\t} else {\n")
				if err := emitNodes(buf, node.ElseBody, validComps); err != nil {
					return err
				}
			}
			buf.WriteString("\t}\n")
		case NodeEach:
			parts := strings.Split(node.Iterator, " as ")
			if len(parts) != 2 {
				return fmt.Errorf("invalid each format: %s", node.Iterator)
			}
			slice := strings.TrimSpace(parts[0])
			vars := strings.Split(parts[1], ",")
			
			varName := "item"
			idxName := "_"
			if len(vars) == 1 {
				varName = strings.TrimSpace(vars[0])
			} else if len(vars) == 2 {
				varName = strings.TrimSpace(vars[0])
				idxName = strings.TrimSpace(vars[1])
			}

			buf.WriteString(fmt.Sprintf("\tfor %s, %s := range %s {\n", idxName, varName, slice))
			if err := emitNodes(buf, node.Body, validComps); err != nil {
				return err
			}
			buf.WriteString("\t}\n")
			
		case NodeComponent:
			// parse pros
			props := parseAttributes(node.TagContent)
			
			// struct initialization
			var structValues []string
			
			for k, v := range props {
				fieldName := k
				if len(fieldName) > 0 {
					fieldName = strings.ToUpper(fieldName[0:1]) + fieldName[1:]
				}
				structValues = append(structValues, fmt.Sprintf("%s: %s", fieldName, v))
			}
			
			structInit := fmt.Sprintf("%sProps{%s}", node.TagName, strings.Join(structValues, ", "))
			
			alias := validComps[node.TagName]
			
			// write component call
			if node.SelfClosing || len(node.Body) == 0 {
				buf.WriteString(fmt.Sprintf("\t%s%s(w, data, %s%s, nil)\n", alias, node.TagName, alias, structInit))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s%s(w, data, %s%s, func() {\n", alias, node.TagName, alias, structInit))
				if err := emitNodes(buf, node.Body, validComps); err != nil {
					return err
				}
				buf.WriteString("\t})\n")
			}
			
		case NodeSlot:
			buf.WriteString("\tif slot != nil {\n\t\tslot()\n\t}\n")
		}
	}
	return nil
}

func emitHTML(buf *bytes.Buffer, content string) {
	if len(content) == 0 {
		return
	}
	// escape ` and write
	escaped := strings.ReplaceAll(content, "`", "`+\"`\"+`")
	buf.WriteString(fmt.Sprintf("\tw.Write([]byte(`%s`))\n", escaped))
}

func emitExpression(buf *bytes.Buffer, expr string) {
	expr = strings.TrimSpace(expr)
	
	// handle raw()
	if strings.HasPrefix(expr, "raw(") && strings.HasSuffix(expr, ")") {
		inner := expr[4 : len(expr)-1]
		buf.WriteString(fmt.Sprintf("\tw.Write([]byte(fmt.Sprint(%s)))\n", inner))
		return
	}
	
	buf.WriteString(fmt.Sprintf("\tw.Write([]byte(html.EscapeString(fmt.Sprint(%s))))\n", expr))
}

func parseAttributes(tagContent string) map[string]string {
	// e.g. <Button title="Hello" count={{ data.Count }} disabled>
	tagContent = strings.TrimSpace(tagContent)
	tagContent = strings.TrimPrefix(tagContent, "<")
	tagContent = strings.TrimSuffix(tagContent, "/>")
	tagContent = strings.TrimSuffix(tagContent, ">")
	
	// strip tag name
	idx := strings.IndexAny(tagContent, " \t\n\r")
	if idx == -1 {
		return nil
	}
	
	attrStr := tagContent[idx+1:]
	matches := attrRegex.FindAllStringSubmatch(attrStr, -1)
	
	props := make(map[string]string)
	
	for _, m := range matches {
		if len(m) == 0 {
			continue
		}
		key := m[1]
		if key == "" {
			continue
		}
		
		val := "true" // boolean prop like `disabled`
		
		if m[2] != "" {
			val = "\"" + m[2] + "\"" // string like "hello"
		} else if m[3] != "" {
			val = "\"" + m[3] + "\"" // string like 'hello'
		} else if m[4] != "" {
			val = m[4] // expression like data.Count
		}
		
		props[key] = val
	}
	
	return props
}
