// Code generated by Stew-Lang. DO NOT EDIT.
package test

import (
	"github.com/ZiplEix/stew/sdk/stew"
	"github.com/ZiplEix/test-stew/component"
	"io"
)

func Page(w io.Writer, data stew.PageData) {

	w.Write([]byte(`

<div class="flex flex-col items-center justify-center min-h-[80vh] font-sans p-6">
    <div class="w-full max-w-4xl">
        <div class="text-center mb-12">
            <h1 class="text-4xl font-black tracking-tighter mb-4">Components Test</h1>
            <p class="text-stone-500 text-lg">Testing the Stew-Lang component system.</p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            `))
	component.Card(w, data, component.CardProps{Title: "User Profile", Description: "A component handling user sessions and data representation."}, func() {
		w.Write([]byte(`
                <button class="bg-stone-900 text-white px-4 py-2 rounded-lg font-medium hover:bg-stone-800">
                    View Profile
                </button>
            `))
	})
	w.Write([]byte(`

            `))
	component.Card(w, data, component.CardProps{Title: "Analytics", Description: "Displaying real-time charts and data directly fetched from Go."}, func() {
		w.Write([]byte(`
                <button class="bg-stone-900 text-white px-4 py-2 rounded-lg font-medium hover:bg-stone-800">
                    Open Dashboard
                </button>
            `))
	})
	w.Write([]byte(`
        </div>
        
        <div class="text-center mt-12">
            <a href="/" class="text-amber-600 font-bold hover:underline">← Back to Home</a>
        </div>
    </div>
</div>
`))
}
