// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package middleware

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 06</div><h1 class=\"text-5xl font-black mb-4\">Middlewares</h1><p class=\"text-xl text-stone-500 leading-relaxed\">Secure your routes and inject data. Middlewares in Stew act as an onion, wrapping your handlers from the root down to the leaf.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The Onion Model</h2><p>Just like layouts, <code>stew.middleware.go</code> files are inherited. A middleware placed at the root will affect <strong>every</strong> single route in your application.</p><div class=\"bg-stone-900 rounded-xl p-6 font-mono text-sm text-stone-400\"><div class=\"flex items-center gap-3\"><span class=\"text-amber-500\">→</span> <span>Root Middleware</span></div><div class=\"flex items-center gap-3 ml-6 mt-2\"><span class=\"text-amber-500\">→</span> <span>Admin Middleware</span></div><div class=\"flex items-center gap-3 ml-12 mt-2\"><span class=\"text-green-500\">✓</span> <span class=\"text-stone-200\">Final Handler (Page or Server)</span></div></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Standard Signature</h2><p>Middlewares use the standard Go <code>http.Handler</code> signature. You must export a function named <code>Middleware</code>.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`package auth

import "net/http"

func Middleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // 1. Logic before (Auth, Logging, etc.)
        if r.Header.Get("Authorization") == "" {
            http.Error(w, "Unauthorized", http.StatusUnauthorized)
            return
        }

        // 2. Call next handler
        next.ServeHTTP(w, r)
    })
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/middleware/stew.page.templ`, Line: 58, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Context Sharing</h2><p>Middlewares can pass data to your pages via the request context. This data is then accessible in your <code>stew.PageData</code>.</p><div class=\"bg-blue-50 border-l-4 border-blue-500 p-6 rounded-r-xl\"><h4 class=\"font-bold text-blue-900 mb-1\">🔗 Integrated Flow</h4><p class=\"text-blue-800 text-sm\">Inject a user ID in the context within your middleware, and retrieve it in your <code>stew.page.templ</code> using <code>data.Request.Context().Value(\"user\")</code>.</p></div></section><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/server-handlers\" class=\"text-stone-400 hover:text-stone-600 transition\">← Server Handlers</a> <a href=\"/guide/pagedata\" class=\"text-amber-600 font-bold hover:underline\">Next: PageData →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
