// Code generated by Stew-Lang. DO NOT EDIT.
package components

import (
	"fmt"
	"html"
	"io"

	"github.com/ZiplEix/stew/v2/sdk/stew"
)

type AlertProps struct {
	Type string // "info", "warning", "error"
}

func Alert(w io.Writer, data stew.PageData, props AlertProps, slot func()) {

	bg := "bg-indigo-50"
	border := "border-indigo-500"
	text := "text-indigo-900"

	if props.Type == "warning" {
		bg = "bg-amber-50"
		border = "border-amber-500"
		text = "text-amber-900"
	} else if props.Type == "error" {
		bg = "bg-rose-50"
		border = "border-rose-500"
		text = "text-rose-900"
	} else if props.Type == "info" {
		bg = "bg-blue-50"
		border = "border-blue-500"
		text = "text-blue-900"
	}

	w.Write([]byte(`

`))
	w.Write([]byte(`<div class="`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(bg))))
	w.Write([]byte(` border-l-4 `))
	w.Write([]byte(html.EscapeString(fmt.Sprint(border))))
	w.Write([]byte(` p-4 rounded-r-xl text-sm space-y-2 `))
	w.Write([]byte(html.EscapeString(fmt.Sprint(text))))
	w.Write([]byte(` mb-6">`))
	w.Write([]byte(`
    `))
	if slot != nil {
		slot()
	}
	w.Write([]byte(`
`))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
`))
}
