// Code generated by Stew-Lang. DO NOT EDIT.
package components

import (
	"github.com/ZiplEix/stew/sdk/stew"
	"io"
)

type CodeProps struct{}

func Code(w io.Writer, data stew.PageData, props CodeProps, slot func()) {

	w.Write([]byte(`

`))
	w.Write([]byte(`<pre class="bg-stone-900 text-stone-100 p-4 rounded-xl overflow-x-auto text-sm my-4 font-mono shadow-sm">`))
	w.Write([]byte(`<code class="block">`))
	if slot != nil {
		slot()
	}
	w.Write([]byte(`</code>`))
	w.Write([]byte(`</pre>`))
	w.Write([]byte(`
`))
}
