// Code generated by Stew-Lang. DO NOT EDIT.
package components

import (
	"fmt"
	"html"
	"io"

	"github.com/ZiplEix/stew/v2/sdk/stew"
)

type NavFooterProps struct {
	PrevLink string
	PrevName string
	NextLink string
	NextName string
}

func NavFooter(w io.Writer, data stew.PageData, props NavFooterProps, slot func()) {

	w.Write([]byte(`

`))
	w.Write([]byte(`<footer class="pt-8 border-t border-stone-100 flex justify-between mt-12">`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`<div id="stew-block-navfooter-0" style="display: contents;">`))
	if props.PrevLink != "" {
		w.Write([]byte(`
        `))
		w.Write([]byte(`<a href="`))
		w.Write([]byte(html.EscapeString(fmt.Sprint(props.PrevLink))))
		w.Write([]byte(`" class="text-stone-400 hover:text-stone-600 transition">`))
		w.Write([]byte(`← `))
		w.Write([]byte(html.EscapeString(fmt.Sprint(props.PrevName))))
		w.Write([]byte(`</a>`))
		w.Write([]byte(`
    `))
	} else {
		w.Write([]byte(`
        `))
		w.Write([]byte(`<div>`))
		w.Write([]byte(`</div>`))
		w.Write([]byte(`
    `))
	}
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`<div id="stew-block-navfooter-1" style="display: contents;">`))
	if props.NextLink != "" {
		w.Write([]byte(`
        `))
		w.Write([]byte(`<a href="`))
		w.Write([]byte(html.EscapeString(fmt.Sprint(props.NextLink))))
		w.Write([]byte(`" class="text-amber-600 font-bold hover:underline">`))
		w.Write([]byte(`Suivant : `))
		w.Write([]byte(html.EscapeString(fmt.Sprint(props.NextName))))
		w.Write([]byte(` →`))
		w.Write([]byte(`</a>`))
		w.Write([]byte(`
    `))
	}
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
`))
	w.Write([]byte(`</footer>`))
	w.Write([]byte(`
`))
}
