// Code generated by Stew-Lang. DO NOT EDIT.
package pages

import (
	"fmt"
	"github.com/ZiplEix/stew/sdk/live"
	"github.com/ZiplEix/stew/sdk/stew"
	"io"
	"os"
)

func Layout(w io.Writer, data stew.PageData, slot func()) {

	w.Write([]byte(`
`))

	w.Write([]byte(`

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Stew App</title>
        <script src="https://unpkg.com/htmx.org@1.9.10"></script>
        <script src="https://unpkg.com/idiomorph/dist/idiomorph-ext.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body hx-ext="morph" class="bg-stone-50 text-stone-900">
        `))
	if slot != nil {
		slot()
	}
	w.Write([]byte(`

        `))
	if os.Getenv("STEW_DEV") == "true" {
		w.Write([]byte(`
            `))
		w.Write([]byte(fmt.Sprint(live.InjectScript())))
		w.Write([]byte(`
        `))
	}
	w.Write([]byte(`
    </body>
</html>
`))
}
