// Code generated by Stew-Lang. DO NOT EDIT.
package pages

import (
	"fmt"
	"github.com/ZiplEix/stew/sdk/live"
	"github.com/ZiplEix/stew/sdk/stew"
	"io"
	"os"
)

func Layout(w io.Writer, data stew.PageData, slot func()) {

	w.Write([]byte(`
`))

	w.Write([]byte(`

`))
	w.Write([]byte(`<!DOCTYPE html>`))
	w.Write([]byte(`
`))
	w.Write([]byte(`<html lang="en">`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`<head>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<meta charset="UTF-8"/>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<meta name="viewport" content="width=device-width, initial-scale=1.0"/>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<title>`))
	w.Write([]byte(`Stew App`))
	w.Write([]byte(`</title>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<script src="https://unpkg.com/htmx.org@1.9.10">`))
	w.Write([]byte(`</script>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<script src="https://unpkg.com/idiomorph/dist/idiomorph-ext.min.js">`))
	w.Write([]byte(`</script>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<script src="https://cdn.tailwindcss.com">`))
	w.Write([]byte(`</script>`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`</head>`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`<body hx-ext="morph" class="bg-stone-50 text-stone-900">`))
	w.Write([]byte(`
        `))
	if slot != nil {
		slot()
	}
	w.Write([]byte(`

        `))
	w.Write([]byte(`<div id="stew-block-layout-0" style="display: contents;">`))
	if os.Getenv("STEW_DEV") == "true" {
		w.Write([]byte(`
            `))
		w.Write([]byte(fmt.Sprint(live.InjectScript())))
		w.Write([]byte(`
        `))
	}
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`</body>`))
	w.Write([]byte(`
`))
	w.Write([]byte(`</html>`))
	w.Write([]byte(`
`))
}
