// Code generated by Stew-Lang. DO NOT EDIT.
package pages

import (
	"encoding/json"
	"fmt"
	"github.com/ZiplEix/stew/sdk/stew"
	"html"
	"io"
	"strconv"
)

func Page(w io.Writer, data stew.PageData) {

	count := 0
	if c := data.Query.Get("count"); c != "" {
		count, _ = strconv.Atoi(c)
	}

	w.Write([]byte(`

`))
	w.Write([]byte(`

`))
	w.Write([]byte(`<div class="flex flex-col items-center justify-center min-h-[80vh] text-center font-sans p-6">`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`<div class="bg-white p-12 rounded-[2.5rem] shadow-xl shadow-stone-200 border border-stone-100">`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<h1 class="text-6xl mb-4">`))
	w.Write([]byte(`🍲`))
	w.Write([]byte(`</h1>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<h2 class="text-4xl font-black tracking-tighter mb-4">`))
	w.Write([]byte(`Stew 2.0 Alpha`))
	w.Write([]byte(`</h2>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<p class="text-stone-500 text-lg mb-8">`))
	w.Write([]byte(`Your Go Fullstack framework is ready to cook.`))
	w.Write([]byte(`</p>`))
	w.Write([]byte(`
        
        `))
	w.Write([]byte(`<!-- Server HTMX Counter -->`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<h3 class="text-xl font-bold mt-12 mb-2 text-stone-700">`))
	w.Write([]byte(`Server Counter (HTMX)`))
	w.Write([]byte(`</h3>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<div id="counter" 
             hx-select="#counter" 
             hx-target="#counter" 
             hx-swap="outerHTML" 
             class="flex items-center justify-center gap-6 mb-10 p-6 bg-stone-50 rounded-3xl border border-stone-100 shadow-inner">`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<button 
                hx-get="/?count=`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count - 1))))
	w.Write([]byte(`" 
                class="w-14 h-14 flex items-center justify-center bg-white border border-stone-200 rounded-2xl text-stone-600 hover:bg-stone-100 hover:text-stone-900 hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold shadow-sm"
            >`))
	w.Write([]byte(`
                -
            `))
	w.Write([]byte(`</button>`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<div class="text-5xl font-black w-24 text-center tabular-nums text-stone-800 tracking-tight">`))
	w.Write([]byte(`
                `))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count))))
	w.Write([]byte(`
            `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<button 
                hx-get="/?count=`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count + 1))))
	w.Write([]byte(`" 
                class="w-14 h-14 flex items-center justify-center bg-stone-900 text-white rounded-2xl hover:bg-stone-800 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold"
            >`))
	w.Write([]byte(`
                +
            `))
	w.Write([]byte(`</button>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`

        `))
	w.Write([]byte(`<!-- Local Wasm Counter -->`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<h3 class="text-xl font-bold mb-2 text-indigo-700">`))
	w.Write([]byte(`Client Counter (Wasm + TinyGo)`))
	w.Write([]byte(`</h3>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<p class="text-stone-500 text-sm mb-4">`))
	w.Write([]byte(`Reacts instantaneously at 60FPS using Signals & Auto-Tracking.`))
	w.Write([]byte(`</p>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`<div class="flex items-center justify-center gap-6 mb-10 p-6 bg-indigo-50/50 rounded-3xl border border-indigo-100 shadow-inner">`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<button 
                 id="stew-bind-page-0" `))
	w.Write([]byte(`
                class="w-14 h-14 flex items-center justify-center bg-white border border-indigo-200 rounded-2xl text-indigo-600 hover:bg-indigo-100 hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold shadow-sm"
            >`))
	w.Write([]byte(`
                -
            `))
	w.Write([]byte(`</button>`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<div class="text-5xl font-black w-24 text-center tabular-nums text-indigo-800 tracking-tight"  id="stew-bind-page-1" `))
	w.Write([]byte(`>`))
	w.Write([]byte(`
                0
            `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
            
            `))
	w.Write([]byte(`<button 
                 id="stew-bind-page-2" `))
	w.Write([]byte(`
                class="w-14 h-14 flex items-center justify-center bg-indigo-600 text-white rounded-2xl hover:bg-indigo-500 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold"
            >`))
	w.Write([]byte(`
                +
            `))
	w.Write([]byte(`</button>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`

        `))
	w.Write([]byte(`<div class="space-y-4">`))
	w.Write([]byte(`
            `))
	w.Write([]byte(`<p class="text-sm text-stone-400">`))
	w.Write([]byte(`Modify `))
	w.Write([]byte(`<code class="bg-stone-100 px-2 py-1 rounded">`))
	w.Write([]byte(`pages/@page.stew`))
	w.Write([]byte(`</code>`))
	w.Write([]byte(` to start.`))
	w.Write([]byte(`</p>`))
	w.Write([]byte(`
            `))
	w.Write([]byte(`<a href="https://github.com/ZiplEix/stew" class="inline-block text-amber-600 font-bold hover:underline">`))
	w.Write([]byte(`
                Read the documentation →
            `))
	w.Write([]byte(`</a>`))
	w.Write([]byte(`
        `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
    `))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
`))
	w.Write([]byte(`</div>`))
	w.Write([]byte(`
`))
	dataJSON, _ := json.Marshal(data)
	w.Write([]byte(`<script type="application/json" id="stew-pagedata">`))
	w.Write(dataJSON)
	w.Write([]byte(`</script>`))
	w.Write([]byte(`<script src="/static/wasm/wasm_exec.js"></script><script>const go = new Go(); WebAssembly.instantiateStreaming(fetch("/static/wasm/pages_page.wasm"), go.importObject).then((result) => { go.run(result.instance); });</script>`))
}
