// Code generated by Stew-Lang. DO NOT EDIT.
package component

import (
	"fmt"
	"github.com/ZiplEix/stew/sdk/stew"
	"html"
	"io"
)

type BadgeProps struct {
	Text string
}

func Badge(w io.Writer, data stew.PageData, props BadgeProps, slot func()) {

	w.Write([]byte(`

<span class="inline-block px-2 py-1 bg-stone-100 text-stone-600 text-xs font-bold rounded-full mb-3 border border-stone-200">
    `))
	w.Write([]byte(html.EscapeString(fmt.Sprint(props.Text))))
	w.Write([]byte(`
</span>
`))
}
