// Code generated by Stew-Lang. DO NOT EDIT.
package component

import (
	"fmt"
	"github.com/ZiplEix/stew/sdk/stew"
	"html"
	"io"
)

type CardProps struct {
	Title       string
	Description string
}

func Card(w io.Writer, data stew.PageData, props CardProps, slot func()) {

	w.Write([]byte(`

<div class="bg-white p-6 rounded-2xl shadow-sm border border-stone-100 hover:shadow-md transition-shadow">
    `))
	Badge(w, data, BadgeProps{Text: "Nested"}, nil)
	w.Write([]byte(`
    <h3 class="text-xl font-bold mb-2 text-stone-800">`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(props.Title))))
	w.Write([]byte(`</h3>
    <p class="text-stone-500 mb-4">`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(props.Description))))
	w.Write([]byte(`</p>
    <div class="text-sm">
        `))
	if slot != nil {
		slot()
	}
	w.Write([]byte(`
    </div>
</div>
`))
}
