// Code generated by Stew. DO NOT EDIT.
package main

import (
	"github.com/ZiplEix/stew/sdk/stew"
	"net/http"

	stew_pages_root "github.com/ZiplEix/test-stew/pages"
	stew_test "github.com/ZiplEix/test-stew/pages/test"
)

func RegisterStewRoutes(mux *http.ServeMux) {
	// --- Route: / ---
	mux.Handle("GET /", stew_pages_root.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_pages_root.Page(w, data)
		})
	})))
	// --- Route: /test ---
	mux.Handle("GET /test", stew_pages_root.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_test.Page(w, data)
		})
	})))
}
