// Code generated by Stew-Lang. DO NOT EDIT.
package pages

import (
	"fmt"
	"github.com/ZiplEix/stew/sdk/stew"
	"html"
	"io"
	"strconv"
)

func Page(w io.Writer, data stew.PageData) {

	w.Write([]byte(`
`))

	count := 0
	if c := data.Query.Get("count"); c != "" {
		count, _ = strconv.Atoi(c)
	}

	w.Write([]byte(`

<div class="flex flex-col items-center justify-center min-h-[80vh] text-center font-sans p-6">
    <div class="bg-white p-12 rounded-[2.5rem] shadow-xl shadow-stone-200 border border-stone-100">
        <h1 class="text-6xl mb-4">🍲</h1>
        <h2 class="text-4xl font-black tracking-tighter mb-4">Stew 2.0 Alpha</h2>
        <p class="text-stone-500 text-lg mb-8">Your Go Fullstack framework is ready to cook.</p>
        
        <!-- Live Counter -->
        <div id="counter" 
             hx-select="#counter" 
             hx-target="#counter" 
             hx-swap="outerHTML" 
             class="flex items-center justify-center gap-6 my-10 p-6 bg-stone-50 rounded-3xl border border-stone-100 shadow-inner">
            
            <button 
                hx-get="/?count=`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count - 1))))
	w.Write([]byte(`" 
                class="w-14 h-14 flex items-center justify-center bg-white border border-stone-200 rounded-2xl text-stone-600 hover:bg-stone-100 hover:text-stone-900 hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold shadow-sm"
            >
                -
            </button>
            
            <div class="text-5xl font-black w-24 text-center tabular-nums text-stone-800 tracking-tight">
                `))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count))))
	w.Write([]byte(`
            </div>
            
            <button 
                hx-get="/?count=`))
	w.Write([]byte(html.EscapeString(fmt.Sprint(count + 1))))
	w.Write([]byte(`" 
                class="w-14 h-14 flex items-center justify-center bg-stone-900 text-white rounded-2xl hover:bg-stone-800 hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0 transition-all text-2xl font-bold"
            >
                +
            </button>
        </div>

        <div class="space-y-4">
            <p class="text-sm text-stone-400">Modify <code class="bg-stone-100 px-2 py-1 rounded">pages/@page.stew</code> to start.</p>
            <a href="https://github.com/ZiplEix/stew" class="inline-block text-amber-600 font-bold hover:underline">
                Read the documentation →
            </a>
        </div>
    </div>
</div>
`))
}
