// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pagedata

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 07</div><h1 class=\"text-5xl font-black mb-4\">Working with PageData</h1><p class=\"text-xl text-stone-500 leading-relaxed\">Dynamic pages need data. Stew automatically injects a <code>PageData</code> object into every page and layout.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The PageData Structure</h2><p>Every <code>Page(data stew.PageData)</code> function receives this structured object containing everything about the current request.</p><div class=\"bg-stone-50 border border-stone-200 rounded-xl p-6 font-mono text-sm\"><ul class=\"space-y-3\"><li><span class=\"text-amber-600 font-bold\">URL</span> <span class=\"text-stone-400 italic\">string</span> - The full request path.</li><li><span class=\"text-amber-600 font-bold\">Params</span> <span class=\"text-stone-400 italic\">map[string]string</span> - Dynamic path segments (e.g. <code>_id_</code>).</li><li><span class=\"text-amber-600 font-bold\">Query</span> <span class=\"text-stone-400 italic\">url.Values</span> - Parsed query string parameters.</li><li><span class=\"text-amber-600 font-bold\">Request</span> <span class=\"text-stone-400 italic\">*http.Request</span> - The raw underlying Go request object.</li></ul></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Practical Example</h2><p>Accessing a user ID from the URL and a search term from the query string is straightforward:</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`templ Page(data stew.PageData) {
    <div>
        <h1>User ID: { data.Params["id"] }</h1>
        <p>Search: { data.Query.Get("q") }</p>
        <p>Current Path: { data.URL }</p>
    </div>
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/pagedata/stew.page.templ`, Line: 44, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Accessing Context</h2><p>Since <code>PageData</code> includes the original Request, you can easily retrieve values injected by your middlewares via the Go context.</p><div class=\"bg-stone-100 p-6 rounded-xl border border-stone-200\"><code class=\"text-sm font-bold text-stone-800\">user := data.Request.Context().Value(\"user\").(MyUserType)</code></div></section><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/middleware\" class=\"text-stone-400 hover:text-stone-600 transition\">← Middlewares</a> <a href=\"/guide/hot-morphing\" class=\"text-amber-600 font-bold hover:underline\">Next: Hot Morphing →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
