// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package guide

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><h1 class=\"text-5xl font-black mb-4\">Introduction</h1><p class=\"text-xl text-stone-500 leading-relaxed\">Stew is designed to make Go web development as intuitive as modern frontend frameworks,  without sacrificing the performance and type-safety of a compiled language.</p></header><section class=\"space-y-4\"><h2 class=\"text-2xl font-bold\">The GOTH Stack Philosophy</h2><p>Stew is the glue for the <strong>GOTH</strong> stack (Go, Templ, HTMX).  Instead of manually wiring routers and handlers, Stew uses your filesystem as the source of truth.</p></section><div class=\"bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl\"><h4 class=\"font-bold text-amber-900 mb-1\">🧑\u200d🍳 Chef's Rule</h4><p class=\"text-amber-800 text-sm\">All special framework files must start with the <code>stew.</code> prefix.  This prevents Go from ignoring them and keeps your workspace organized.</p></div><section class=\"space-y-4\"><h2 class=\"text-2xl font-bold\">Project Structure</h2><p>A typical Stew project looks like this:</p><div class=\"bg-stone-900 text-stone-300 p-6 rounded-xl font-mono text-sm shadow-inner\"><ul class=\"space-y-1\"><li>.</li><li>├── main.go <span class=\"text-stone-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("// Entry point").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></li><li>├── stew_router_gen.go <span class=\"text-stone-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("// Autogenerated").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></li><li>└── pages/</li><li class=\"pl-4\">├── stew.layout.templ <span class=\"text-stone-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("// Root Layout").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></li><li class=\"pl-4\">├── stew.page.templ <span class=\"text-stone-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("// Home (/)").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span></li><li class=\"pl-4\">└── api/</li><li class=\"pl-8\">└── hello/</li><li class=\"pl-12\">└── stew.server.go <span class=\"text-stone-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("// POST /api/hello").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></li></ul></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
