// Code generated by Stew. DO NOT EDIT.
package main

import (
	"github.com/ZiplEix/stew/sdk/stew"
	"github.com/a-h/templ"
	"net/http"

	stew_pages_root "github.com/ZiplEix/stew/doc/pages"
	stew_guide "github.com/ZiplEix/stew/doc/pages/guide"
	stew_guide_assets_tailwind "github.com/ZiplEix/stew/doc/pages/guide/assets-tailwind"
	stew_guide_configuration "github.com/ZiplEix/stew/doc/pages/guide/configuration"
	stew_guide_deployment "github.com/ZiplEix/stew/doc/pages/guide/deployment"
	stew_guide_files "github.com/ZiplEix/stew/doc/pages/guide/files"
	stew_guide_hot_morphing "github.com/ZiplEix/stew/doc/pages/guide/hot-morphing"
	stew_guide_installation "github.com/ZiplEix/stew/doc/pages/guide/installation"
	stew_guide_layouts "github.com/ZiplEix/stew/doc/pages/guide/layouts"
	stew_guide_middleware "github.com/ZiplEix/stew/doc/pages/guide/middleware"
	stew_guide_pagedata "github.com/ZiplEix/stew/doc/pages/guide/pagedata"
	stew_guide_routing "github.com/ZiplEix/stew/doc/pages/guide/routing"
	stew_guide_server_handlers "github.com/ZiplEix/stew/doc/pages/guide/server-handlers"
)

func RegisterStewRoutes(mux *http.ServeMux) {
	// --- Route: / ---
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_pages_root.Page(data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide ---
	mux.Handle("GET /guide", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/assets-tailwind ---
	mux.Handle("GET /guide/assets-tailwind", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_assets_tailwind.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/configuration ---
	mux.Handle("GET /guide/configuration", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_configuration.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/deployment ---
	mux.Handle("GET /guide/deployment", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_deployment.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/files ---
	mux.Handle("GET /guide/files", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_files.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/hot-morphing ---
	mux.Handle("GET /guide/hot-morphing", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_hot_morphing.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/installation ---
	mux.Handle("GET /guide/installation", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_installation.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/layouts ---
	mux.Handle("GET /guide/layouts", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_layouts.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/middleware ---
	mux.Handle("GET /guide/middleware", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_middleware.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/pagedata ---
	mux.Handle("GET /guide/pagedata", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_pagedata.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/routing ---
	mux.Handle("GET /guide/routing", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_routing.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
	// --- Route: /guide/server-handlers ---
	mux.Handle("GET /guide/server-handlers", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_guide.Layout(stew_guide_server_handlers.Page(data), data), data)
		templ.Handler(component).ServeHTTP(w, r)
	}))
}
