// Code generated by Stew. DO NOT EDIT.
package main

import (
	"github.com/ZiplEix/stew/sdk/stew"
	"net/http"

	stew_pages_root "github.com/ZiplEix/stew/doc/pages"
	stew_guide "github.com/ZiplEix/stew/doc/pages/guide"
	stew_guide_assets "github.com/ZiplEix/stew/doc/pages/guide/assets"
	stew_guide_cli "github.com/ZiplEix/stew/doc/pages/guide/cli"
	stew_guide_components "github.com/ZiplEix/stew/doc/pages/guide/components"
	stew_guide_configuration "github.com/ZiplEix/stew/doc/pages/guide/configuration"
	stew_guide_deployment "github.com/ZiplEix/stew/doc/pages/guide/deployment"
	stew_guide_goscriptclient "github.com/ZiplEix/stew/doc/pages/guide/goscriptclient"
	stew_guide_goscriptserver "github.com/ZiplEix/stew/doc/pages/guide/goscriptserver"
	stew_guide_hotmorphing "github.com/ZiplEix/stew/doc/pages/guide/hotmorphing"
	stew_guide_installation "github.com/ZiplEix/stew/doc/pages/guide/installation"
	stew_guide_internals "github.com/ZiplEix/stew/doc/pages/guide/internals"
	stew_guide_layouts "github.com/ZiplEix/stew/doc/pages/guide/layouts"
	stew_guide_middleware "github.com/ZiplEix/stew/doc/pages/guide/middleware"
	stew_guide_packages "github.com/ZiplEix/stew/doc/pages/guide/packages"
	stew_guide_packages_anim "github.com/ZiplEix/stew/doc/pages/guide/packages/anim"
	stew_guide_packages_cookies "github.com/ZiplEix/stew/doc/pages/guide/packages/cookies"
	stew_guide_packages_data "github.com/ZiplEix/stew/doc/pages/guide/packages/data"
	stew_guide_packages_event "github.com/ZiplEix/stew/doc/pages/guide/packages/event"
	stew_guide_packages_io "github.com/ZiplEix/stew/doc/pages/guide/packages/io"
	stew_guide_packages_nav "github.com/ZiplEix/stew/doc/pages/guide/packages/nav"
	stew_guide_packages_reference "github.com/ZiplEix/stew/doc/pages/guide/packages/reference"
	stew_guide_packages_state "github.com/ZiplEix/stew/doc/pages/guide/packages/state"
	stew_guide_packages_storage "github.com/ZiplEix/stew/doc/pages/guide/packages/storage"
	stew_guide_packages_ui "github.com/ZiplEix/stew/doc/pages/guide/packages/ui"
	stew_guide_pagedata "github.com/ZiplEix/stew/doc/pages/guide/pagedata"
	stew_guide_reservedfiles "github.com/ZiplEix/stew/doc/pages/guide/reservedfiles"
	stew_guide_routing "github.com/ZiplEix/stew/doc/pages/guide/routing"
	stew_guide_serverhandlers "github.com/ZiplEix/stew/doc/pages/guide/serverhandlers"
	stew_guide_syntax "github.com/ZiplEix/stew/doc/pages/guide/syntax"
	stew_guide_troubleshooting "github.com/ZiplEix/stew/doc/pages/guide/troubleshooting"
	stew_guide_wasmbindings "github.com/ZiplEix/stew/doc/pages/guide/wasmbindings"
	stew_guide_wasmsdk "github.com/ZiplEix/stew/doc/pages/guide/wasmsdk"
	stew_test "github.com/ZiplEix/stew/doc/pages/test"
	stew_test_id "github.com/ZiplEix/stew/doc/pages/test/__id__"
	stew_test_reactive "github.com/ZiplEix/stew/doc/pages/test_reactive"
)

func RegisterStewRoutes(mux *http.ServeMux) {
	// Serve static assets (like CSS, Wasm binaries, etc)
	mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
	// --- Route: / ---
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_pages_root.Page(w, data)
		})
	}))
	// --- Route: /guide ---
	mux.Handle("GET /guide", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/assets ---
	mux.Handle("GET /guide/assets", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_assets.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/cli ---
	mux.Handle("GET /guide/cli", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_cli.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/components ---
	mux.Handle("GET /guide/components", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_components.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/configuration ---
	mux.Handle("GET /guide/configuration", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_configuration.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/deployment ---
	mux.Handle("GET /guide/deployment", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_deployment.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/goscriptclient ---
	mux.Handle("GET /guide/goscriptclient", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_goscriptclient.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/goscriptserver ---
	mux.Handle("GET /guide/goscriptserver", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_goscriptserver.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/hotmorphing ---
	mux.Handle("GET /guide/hotmorphing", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_hotmorphing.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/installation ---
	mux.Handle("GET /guide/installation", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_installation.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/internals ---
	mux.Handle("GET /guide/internals", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_internals.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/layouts ---
	mux.Handle("GET /guide/layouts", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_layouts.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/middleware ---
	mux.Handle("GET /guide/middleware", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_middleware.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages ---
	mux.Handle("GET /guide/packages", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/anim ---
	mux.Handle("GET /guide/packages/anim", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_anim.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/cookies ---
	mux.Handle("GET /guide/packages/cookies", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_cookies.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/data ---
	mux.Handle("GET /guide/packages/data", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_data.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/event ---
	mux.Handle("GET /guide/packages/event", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_event.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/io ---
	mux.Handle("GET /guide/packages/io", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_io.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/nav ---
	mux.Handle("GET /guide/packages/nav", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_nav.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/reference ---
	mux.Handle("GET /guide/packages/reference", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_reference.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/state ---
	mux.Handle("GET /guide/packages/state", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_state.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/storage ---
	mux.Handle("GET /guide/packages/storage", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_storage.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/packages/ui ---
	mux.Handle("GET /guide/packages/ui", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_packages_ui.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/pagedata ---
	mux.Handle("GET /guide/pagedata", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_pagedata.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/reservedfiles ---
	mux.Handle("GET /guide/reservedfiles", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_reservedfiles.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/routing ---
	mux.Handle("GET /guide/routing", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_routing.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/serverhandlers ---
	mux.Handle("GET /guide/serverhandlers", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_serverhandlers.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/syntax ---
	mux.Handle("GET /guide/syntax", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_syntax.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/troubleshooting ---
	mux.Handle("GET /guide/troubleshooting", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_troubleshooting.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/wasmbindings ---
	mux.Handle("GET /guide/wasmbindings", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_wasmbindings.Page(w, data)
			})
		})
	}))
	// --- Route: /guide/wasmsdk ---
	mux.Handle("GET /guide/wasmsdk", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_guide.Layout(w, data, func() {
				stew_guide_wasmsdk.Page(w, data)
			})
		})
	}))
	// --- Route: /test ---
	mux.Handle("GET /test", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_test.Page(w, data)
		})
	}))
	// --- Route: /test/{id} ---
	mux.Handle("GET /test/{id}", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		data.Params["id"] = r.PathValue("id")

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_test_id.Page(w, data)
		})
	}))
	// --- Route: /test_reactive ---
	mux.Handle("GET /test_reactive", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_test_reactive.Page(w, data)
		})
	}))
}
