// Code generated by Stew. DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/ZiplEix/stew/sdk/stew"

	stew_pages_root "stew-demo/pages"
)

func RegisterStewRoutes(mux *http.ServeMux) {
	// Serve static assets (like CSS, Wasm binaries, etc)
	mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
	// --- Route: / ---
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		// Appel direct de la fonction de rendu Stew-Lang
		stew_pages_root.Layout(w, data, func() {
			stew_pages_root.Page(w, data)
		})
	}))
}
