// Code generated by Stew. DO NOT EDIT.
package main

import (
	"net/http"

	"github.com/ZiplEix/stew/sdk/stew"
	"github.com/a-h/templ"

	stew_pages_root "github.com/ZiplEix/stew/stew-demo/pages"
)

func RegisterStewRoutes(mux *http.ServeMux) {
	// --- Route: / ---
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		component := stew_pages_root.Layout(stew_pages_root.Page(data))
		templ.Handler(component).ServeHTTP(w, r)
	}))
}
