// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package assetstailwind

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 09</div><h1 class=\"text-5xl font-black mb-4\">Assets & Tailwind</h1><p class=\"text-xl text-stone-500 leading-relaxed\">Managing static files and modern CSS in a Go environment. Stew stays out of your way while keeping your binary portable.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Serving Static Files</h2><p>The standard way to serve assets in Stew is to create a <code>public/</code> folder at the root of your project. You can then use a simple <code>http.FileServer</code> in your <code>main.go</code>.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`// In your main.go
mux := http.NewServeMux()
fs := http.FileServer(http.Dir("./public"))
mux.Handle("GET /public/", http.StripPrefix("/public/", fs))`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/assets-tailwind/stew.page.templ`, Line: 25, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Tailwind CSS Integration</h2><p>Since Stew uses <code>.templ</code> files, you need to tell Tailwind to scan them for utility classes. Your <code>tailwind.config.js</code> should look like this:</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`module.exports = {
  content: [
    "./pages/**/*.templ",
    "./pages/**/*.go",
    "./sdk/**/*.templ",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/assets-tailwind/stew.page.templ`, Line: 47, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</pre></div><div class=\"bg-stone-100 p-4 rounded-lg border border-stone-200\"><p class=\"text-sm text-stone-600\"><strong>Pro Tip:</strong> Add the Tailwind build command to your <code>.stew.yaml</code> scripts to automate CSS compilation during <code>stew run dev</code>.</p></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold italic text-amber-700 underline\">Production: The Embed Approach</h2><p>To keep your application as a <strong>single binary</strong>, use Go's <code>embed</code> package. This bundles your CSS and images directly into the executable.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`//go:embed public/*
var staticFS embed.FS

func main() {
    // ...
    fs := http.FileServer(http.FS(staticFS))
    mux.Handle("GET /public/", fs)
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/assets-tailwind/stew.page.templ`, Line: 71, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</pre></div></section><div class=\"bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl\"><h4 class=\"font-bold text-amber-900 mb-1\">🚀 Performance</h4><p class=\"text-amber-800 text-sm\">In production, consider adding a middleware to set <code>Cache-Control</code> headers for your <code>/public/</code> routes to ensure lightning-fast asset delivery.</p></div><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/hot-morphing\" class=\"text-stone-400 hover:text-stone-600 transition\">← Hot Morphing</a> <a href=\"/guide/files\" class=\"text-amber-600 font-bold hover:underline\">Next: Files →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
