// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package deployment

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 11</div><h1 class=\"text-5xl font-black mb-4\">Deployment & Docker</h1><p class=\"text-xl text-stone-500 leading-relaxed\">From your local kitchen to the cloud. Stew applications are compiled into a single, dependency-free binary, making them perfect for containerization.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The Build Process</h2><p>Before shipping, you must run the sequential build command. This ensures that the router is up-to-date and all Templ components are compiled into Go code before the final binary is created.</p><div class=\"bg-stone-900 rounded-xl p-5 shadow-inner\"><code class=\"text-amber-400 font-mono text-sm\">stew build</code></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Multi-Stage Dockerfile</h2><p>The most efficient way to deploy is a multi-stage Docker build. We use a heavy image to build the app and a tiny <code>alpine</code> or <code>scratch</code> image to run it.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`# Build Stage
FROM golang:1.22-alpine AS builder

# Install Stew
RUN go install github.com/ZiplEix/stew@latest

WORKDIR /app
COPY . .

# Build the production binary
RUN stew build

# Run Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/bin/app .
COPY --from=builder /app/.env .

EXPOSE 8080
CMD ["./app"]`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/deployment/stew.page.templ`, Line: 56, Col: 14}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><div class=\"bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl\"><h4 class=\"font-bold text-amber-900 mb-1\">📦 Static Assets</h4><p class=\"text-amber-800 text-sm leading-relaxed\">If your app uses static files (images, CSS, JS), we recommend using Go's <code>embed</code> package to include them directly in the binary. This keeps your Docker image clean and your deployment atomic.</p></div><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Environment Variables</h2><p>In production, Stew ignores <code>.env.local</code> and prioritizes system environment variables. Make sure your hosting provider (Fly.io, Railway, DigitalOcean) has the correct variables set.</p><ul class=\"list-disc list-inside text-stone-600 ml-4 space-y-2\"><li><code class=\"text-stone-900 font-semibold\">PORT</code>: The port your app will listen on (default 8080).</li><li><code class=\"text-stone-900 font-semibold\">STEW_DEV</code>: Set to <code>false</code> to disable Hot Morphing scripts.</li></ul></section><footer class=\"pt-10 border-t border-stone-100 flex justify-center\"><div class=\"text-center\"><p class=\"text-stone-400 mb-4 text-sm font-medium italic\">Congratulations! You've mastered the Stew basics.</p><a href=\"/\" class=\"px-8 py-3 bg-stone-900 text-white rounded-xl font-bold hover:bg-stone-800 transition shadow-lg shadow-stone-200 inline-block\">Back to Home</a></div></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
