// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package configuration

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 02</div><h1 class=\"text-5xl font-black mb-4\">Configuration</h1><p class=\"text-xl text-stone-500 leading-relaxed\">The <code>.stew.yaml</code> file is the brain of your project. It defines how your application is built, run, and which tools it depends on.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The YAML Structure</h2><p>When you run <code>stew init</code>, a default configuration is created. It manages the parallel execution of your development tools.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`commands:
  dev:
    parallel: true
    scripts:
      - name: stew
        run: stew generate --watch
      - name: templ
        run: templ generate --watch
      - name: app
        run: air`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/configuration/stew.page.templ`, Line: 32, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-8\"><h2 class=\"text-2xl font-bold\">Key Sections</h2><div class=\"space-y-3\"><h3 class=\"text-xl font-bold text-amber-600\">commands</h3><p class=\"text-stone-600 text-sm\">Defines your workflows. Each command (like <code>dev</code> or <code>build</code>) contains a list of scripts.</p><ul class=\"list-disc list-inside text-sm text-stone-500 ml-4 space-y-1\"><li><code>parallel: true</code>: Runs all scripts simultaneously (ideal for dev).</li><li><code>parallel: false</code>: Runs scripts sequentially (ideal for CI/CD or production builds).</li></ul></div><div class=\"space-y-3\"><h3 class=\"text-xl font-bold text-amber-600\">requires</h3><p class=\"text-stone-600 text-sm\">Stew acts as a package manager for your dev tools. </p><div class=\"bg-stone-50 border border-stone-200 p-4 rounded-lg font-mono text-xs\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`requires:
  - name: templ
    package: github.com/a-h/templ/cmd/templ@latest`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/configuration/stew.page.templ`, Line: 59, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><p class=\"text-stone-500 text-sm\">Running <code>stew install</code> will automatically download and install these binaries into your GOBIN.</p></div><div class=\"space-y-3\"><h3 class=\"text-xl font-bold text-amber-600\">env_files</h3><p class=\"text-stone-600 text-sm\">A list of <code>.env</code> files to load before executing any command. Stew supports local overrides (e.g., <code>.env.local</code>) out of the box.</p></div></section><div class=\"bg-blue-50 border-l-4 border-blue-500 p-6 rounded-r-xl font-sans\"><h4 class=\"font-bold text-blue-900 mb-1\">🎨 Customizing Output</h4><p class=\"text-blue-800 text-sm leading-relaxed\">You can even customize the <strong>colors</strong> of the logs in your terminal by modifying the <code>colors</code> array. Each script in parallel mode will pick a unique color from this list.</p></div><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Example: Production Build</h2><p>For a production environment, you want a sequential execution to ensure the router is generated before the Go compiler starts:</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(`build:
  parallel: false
  scripts:
    - name: generate
      run: stew generate
    - name: templ
      run: templ generate
    - name: compile
      run: go build -o ./bin/app .`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/configuration/stew.page.templ`, Line: 94, Col: 35}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</pre></div></section><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/installation\" class=\"text-stone-400 hover:text-stone-600 transition\">← Installation</a> <a href=\"/guide/routing\" class=\"text-amber-600 font-bold hover:underline\">Next: Routing →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
