// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 03</div><h1 class=\"text-5xl font-black mb-4\">Layouts & Nesting</h1><p class=\"text-xl text-stone-500 leading-relaxed\">Stop repeating your HTML boilerplate. Stew's recursive nesting allows you to wrap your pages in multiple layers of UI automatically.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The Recursive Chain</h2><p>When a user visits a route, Stew's generator crawls from the root <code>pages/</code> directory down to the target folder. It collects every <code>stew.layout.templ</code> it finds along the way and chains them together.</p><div class=\"bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl\"><h4 class=\"font-bold text-amber-900 mb-1\">The Rendering Order</h4><p class=\"text-amber-800 text-sm\">If a user visits <code>/dashboard/settings</code>, the framework automatically produces: <br><span class=\"font-mono font-bold italic\">RootLayout( DashboardLayout( SettingsPage() ) )</span></p></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Defining a Layout</h2><p>Every <code>stew.layout.templ</code> must accept a <code>templ.Component</code> as its first argument (usually named <code>contents</code>). This is where the child layout or the final page will be injected.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`package pages

templ Layout(contents templ.Component) {
    <div class="main-wrapper">
        <nav>My Global Navbar</nav>
        <main>
            @contents
        </main>
    </div>
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/layouts/stew.page.templ`, Line: 47, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Why Use Nested Layouts?</h2><div class=\"grid md:grid-cols-2 gap-6\"><div class=\"p-6 bg-white border border-stone-200 rounded-xl\"><h4 class=\"font-bold mb-2\">Scoped Sidebars</h4><p class=\"text-sm text-stone-500\">Add a sidebar only to your <code>/docs</code> section by placing a layout in that folder. It won't affect your landing page.</p></div><div class=\"p-6 bg-white border border-stone-200 rounded-xl\"><h4 class=\"font-bold mb-2\">Contextual Data</h4><p class=\"text-sm text-stone-500\">Layouts have access to <code>PageData</code>. Use it to highlight the active tab in a sub-navigation menu based on the URL.</p></div></div></section><div class=\"bg-stone-100 p-6 rounded-xl border border-stone-200\"><h4 class=\"font-bold mb-2\">Zero Configuration</h4><p class=\"text-stone-600 text-sm\">You don't need to manually import or call parent layouts in your files. Their mere existence in a parent directory is enough for Stew to include them in the stack.</p></div><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/routing\" class=\"text-stone-400 hover:text-stone-600 transition\">← Routing</a> <a href=\"/guide/middleware\" class=\"text-amber-600 font-bold hover:underline\">Next: Middlewares →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
