// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package serverhandlers

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ZiplEix/stew/sdk/stew"

func Page(data stew.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-10\"><header><div class=\"text-amber-600 font-mono text-sm mb-2\">Guide / 10</div><h1 class=\"text-5xl font-black mb-4\">Server Handlers</h1><p class=\"text-xl text-stone-500 leading-relaxed\">When you need more than just UI. <code>stew.server.go</code> files handle your API logic, form submissions, and data mutations.</p></header><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The Convention</h2><p>Inside a <code>stew.server.go</code> file, Stew looks for functions named after HTTP verbs (Post, Put, Delete, Patch, Options). These functions must match the standard Go <code>http.HandlerFunc</code> signature.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(`package users

import "net/http"

func Post(w http.ResponseWriter, r *http.Request) {
    // Handle form submission or JSON API
    w.WriteHeader(http.StatusCreated)
    w.Write([]byte("User created!"))
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/server-handlers/stew.page.templ`, Line: 30, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">The GET Priority Rule</h2><p>A directory can contain both a Page and a Server file. However, Stew follows a strict rule for the <code>GET</code> method:</p><div class=\"bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-xl\"><ul class=\"space-y-2 text-amber-900 text-sm\"><li><strong>If <code>stew.page.templ</code> exists:</strong> It always handles the GET request. Any <code>Get()</code> function in the server file will be ignored.</li><li><strong>If only <code>stew.server.go</code> exists:</strong> Your <code>Get()</code> function will be used (perfect for JSON APIs).</li></ul></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Working with HTMX</h2><p>Stew and HTMX are best friends. When handling a POST request from a form, you can return a small Templ fragment or trigger a client-side redirect.</p><div class=\"bg-stone-900 rounded-2xl p-8 shadow-2xl border border-stone-800\"><pre class=\"text-amber-100 font-mono text-sm leading-relaxed overflow-x-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`func Post(w http.ResponseWriter, r *http.Request) {
    err := r.ParseForm()
    if err != nil {
        http.Error(w, "Bad Request", http.StatusBadRequest)
        return
    }

    // After mutation, tell HTMX to redirect the whole page
    w.Header().Set("HX-Redirect", "/dashboard")
    w.WriteHeader(http.StatusNoContent)
}`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/guide/server-handlers/stew.page.templ`, Line: 65, Col: 2}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</pre></div></section><section class=\"space-y-6\"><h2 class=\"text-2xl font-bold\">Accessing Path Parameters</h2><p>Just like in your Pages, you can access dynamic parameters (from <code>_id_</code> folders) using the standard Go 1.22 <code>r.PathValue()</code> method.</p><div class=\"bg-stone-100 p-6 rounded-xl border border-stone-200\"><code class=\"text-sm font-bold text-stone-800 italic\">id := r.PathValue(\"id\")</code></div></section><footer class=\"pt-10 border-t border-stone-100 flex justify-between\"><a href=\"/guide/middleware\" class=\"text-stone-400 hover:text-stone-600 transition\">← Middlewares</a> <a href=\"/guide/pagedata\" class=\"text-amber-600 font-bold hover:underline\">Next: Working with PageData →</a></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
