package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const routerTemplate = `// Code generated by Stew. DO NOT EDIT.
package main

import (
	"net/http"
	"github.com/a-h/templ"
	"github.com/ZiplEix/stew/sdk/stew"
	{{range .Imports}}
	{{.Alias}} "{{.Path}}"
	{{- end}}
)

func RegisterStewRoutes(mux *http.ServeMux) {
	{{- range .Routes}}
	{{- $route := .}}
	// --- Route: {{$route.URLPath}} ---
	{{- if $route.HasPage}}
	mux.Handle("GET {{$route.URLPath}}", {{$route.MiddlewareChain}}http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		data := stew.PageData{
			URL:     r.URL.Path,
			Query:   r.URL.Query(),
			Params:  make(map[string]string),
			Request: r,
			Store:   make(map[string]any),
		}

		{{range $route.ParamKeys}}
		data.Params["{{.}}"] = r.PathValue("{{.}}")
		{{- end}}

		component := {{$route.LayoutChain}}{{$route.PackageAlias}}.Page(data){{$route.CloseParens}}
		templ.Handler(component).ServeHTTP(w, r)
	}){{stringsRepeat ")" (len (split $route.MiddlewareChain "(") | add -1)}})
	{{- end}}
	
	{{- if $route.HasServer}}
	{{- range $route.Methods}}
	{{- if ne (toUpper .) "GET" | or (not $route.HasPage)}}
	mux.Handle("{{toUpper .}} {{$route.URLPath}}", {{$route.MiddlewareChain}}http.HandlerFunc({{$route.PackageAlias}}.{{.}}){{stringsRepeat ")" (len (split $route.MiddlewareChain "(") | add -1)}})
	{{- end}}
	{{- end}}
	{{- end}}
	{{- end}}
}
`

type Writer struct {
	Root *RouteNode
}

func NewWriter(root *RouteNode) *Writer {
	return &Writer{Root: root}
}

func (w *Writer) Generate(outputPath string) error {
	funcMap := template.FuncMap{
		"stringsRepeat": strings.Repeat,
		"split":         strings.Split,
		"toUpper":       strings.ToUpper,
		"add": func(a, b int) int {
			return a + b
		},
	}

	tmpl, err := template.New("stew_router").Funcs(funcMap).Parse(routerTemplate)
	if err != nil {
		return err
	}

	data := w.prepareData()

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println("⚠️  Format error (check generated code):", err)
		return os.WriteFile(outputPath, buf.Bytes(), 0644)
	}

	return os.WriteFile(outputPath, formatted, 0644)
}

type ImportData struct {
	Alias string
	Path  string
}

type TemplateData struct {
	Imports []ImportData
	Routes  []RouteData
}

type RouteData struct {
	URLPath         string
	PackageAlias    string
	HasPage         bool
	HasServer       bool
	Methods         []string
	MiddlewareChain string
	LayoutChain     string
	CloseParens     string
	ParamKeys       []string
}

func (w *Writer) prepareData() TemplateData {
	var routes []RouteData
	importMap := make(map[string]string)

	var walk func(n *RouteNode)
	walk = func(n *RouteNode) {
		if n.HasPage || n.HasServer || n.HasLayout || n.HasMiddleware {
			importMap[n.PackageAlias] = n.ImportPath
		}

		if n.HasPage || n.HasServer {
			mwChain, mwCount := w.buildMiddlewareChain(n)
			lyChain, lyCount := w.buildLayoutChain(n)

			params := extractParamKeys(n.URLPath)

			routes = append(routes, RouteData{
				URLPath:         n.URLPath,
				PackageAlias:    n.PackageAlias,
				HasPage:         n.HasPage,
				HasServer:       n.HasServer,
				Methods:         n.Methods,
				MiddlewareChain: mwChain,
				LayoutChain:     lyChain,
				CloseParens:     strings.Repeat(")", mwCount+lyCount),
				ParamKeys:       params,
			})
		}

		for _, child := range n.Children {
			walk(child)
		}
	}
	walk(w.Root)

	var imports []ImportData
	for alias, path := range importMap {
		imports = append(imports, ImportData{Alias: alias, Path: path})
	}

	return TemplateData{
		Imports: imports,
		Routes:  routes,
	}
}

func extractParamKeys(path string) []string {
	var keys []string
	parts := strings.SplitSeq(path, "/")
	for part := range parts {
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			keys = append(keys, part[1:len(part)-1])
		}
	}
	return keys
}

func (w *Writer) buildMiddlewareChain(n *RouteNode) (string, int) {
	var mws []string
	curr := n
	for curr != nil {
		if curr.HasMiddleware {
			mws = append([]string{curr.PackageAlias + ".Middleware("}, mws...)
		}
		curr = curr.Parent
	}
	return strings.Join(mws, ""), len(mws)
}

func (w *Writer) buildLayoutChain(n *RouteNode) (string, int) {
	var layouts []string
	curr := n
	for curr != nil {
		if curr.HasLayout {
			layouts = append([]string{curr.PackageAlias + ".Layout("}, layouts...)
		}
		curr = curr.Parent
	}
	return strings.Join(layouts, ""), len(layouts)
}
